# 2024-12-29

name: b1
description: b1

runs:
  using: composite
  steps:
    # - uses: actions/checkout@v4
    - name: Bash
      run: |
        echo "Hi from b1!"
        ls -l
      shell: bash
