# 2024-12-29

name: Pipeline p1.yml

on:
  push:
  workflow_dispatch:  # we can also run it manually

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/a1
      - uses: ./.github/actions/b1
