# 2024-12-29

name: Pipeline p1.yml

on:
  workflow_call:

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # caller's
      - uses: actions/checkout@v4  # this wf repo
        with:
          repository: SV-ICA/rP
          ref: main
          path: rP
      - run: |
          ls -al
          ls -al .*
          ls -al *
          ls -al rP/
      - uses: ./rP/.github/actions/a1
      - uses: ./rP/.github/actions/b1
