# 2024-12-29

name: Pipeline p1.yml

on:
  workflow_call:

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # caller's
      # NO need!!!- uses: actions/checkout@v4  # this wf repo
      #   with:
      #     repository: SV-ICA/rP
      #     ref: main
      #     path: rP
      - run: |
          pwd
          ls -al
          ls -al .*
          ls -al *
          # ls -al rP/
          # ls -al rP/.github
          # ls -al rP/.github/actions
          # ls -al rP/.github/actions/a1
          # ls -al rP/.github/actions/b1
          # pwd
      - uses: SV-ICA/.github/actions/a1
      - uses: SV-ICA/.github/actions/b1
